"""Shrink-only guard on the repository's shape baseline (reflection ticket R-11).

Defect class: a repository-shape number ("162 complexity findings", "21 orphan
modules") stated in prose that nothing re-measures -- true the day it is
written and unfalsifiable after -- and, one layer up, a recorded count edited
by hand so a red check goes green without the tree changing.

Mechanism: ``config/shape_baseline.yaml`` is generated by
``python -m scripts.measure_shape write``. This guard re-measures the nine
metrics with the same functions and applies
``scripts.measure_shape.compare_count`` per metric:

* ``actual <= recorded`` -- the shape may only shrink;
* ``actual < recorded`` is accepted only when some input *that metric reads*
  differs from the tree the baseline was generated on (one hash per input
  root, ``scripts.measure_shape.metric_inputs``; schema 2, PR #151). With
  those inputs byte-identical nothing can have improved, so a larger recorded
  number was edited by hand and the failure names the regeneration command.

Hermetic except for one ``ruff`` subprocess (``ruff==0.15.8`` pinned in the
``dev`` extra, which every CI lane that runs ``tests/docs/`` installs). Three
of the nine counts are ruff's, so the guard also requires the installed ruff
to be the version the baseline records. Measured runtime: ~6.5 s for the
module (33 tests, one ``measure`` per module).

Mutations (3 planted defects, each killed by a NAMED test; none carries
``gpu_required`` / ``fem_required``; ``src/`` is byte-identical to the
committed baseline for 2 and 3, which is the state that makes them live):

1. **Growth** -- an untracked ``src/_shape_probe.py`` carrying a lazy ``src``
   import, a library ``print``, a ``"cuda" if torch.cuda.is_available()``
   site, a ``PLR2004`` magic value and no importer. Killed by
   ``test_metric_has_not_grown[lazy_first_party_imports]``,
   ``[library_print_findings]``, ``[adhoc_device_resolution_sites]``,
   ``[orphan_modules]``, ``[magic_value_findings]`` and
   ``test_magic_value_table_has_not_grown`` (7 failed with the end-to-end
   ``test_the_full_comparison_is_clean``, 26 passed).
2. **Hand-lowered record** -- ``complexity_findings`` 162 -> 161 in the YAML.
   Killed by ``test_metric_has_not_grown[complexity_findings]`` ("grew").
3. **Hand-raised record (padding)** -- ``complexity_findings`` 162 -> 170.
   Killed by ``test_recorded_count_is_not_hand_edited[complexity_findings]``,
   whose message carries the regenerate hint.

Control: planting (1) and then running ``write`` makes all 33 pass -- a real
change regenerates the file and is accepted; deleting the probe and restoring
the YAML leaves it byte-identical. (162 is the 2026-09-11 value; the live
number is in the YAML.)

The adjacent weaker defect, found by the first run of mutation 1: the probe's
comment ``# library print, no __main__ here`` contains the literal
``__main__``, and the Appendix A substring split (``"__main__" in text``)
classified the file as a CLI module, so ``[library_print_findings]`` stayed
green on a planted library print. The block is now detected by AST
(``scripts.measure_shape.has_main_block``); the live count is 17 either way.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Final

import pytest

from scripts.measure_shape import (
    DEFAULT_BASELINE,
    METRIC_NAMES,
    REGENERATE_HINT,
    SHAPE_BASELINE_SCHEMA_VERSION,
    TABLE_NAMES,
    VIOLATION_KINDS,
    ShapeBaseline,
    ShapeConfig,
    compare,
    compare_count,
    input_roots,
    inputs_unchanged,
    load_baseline,
    measure,
    metric_inputs,
    python_files_under,
    ruff_version,
)

REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[2]
BASELINE_PATH: Final[Path] = REPO_ROOT / "config" / "shape_baseline.yaml"

#: The ticket names nine metrics. Pinned so a tenth cannot be added (or one
#: dropped) without this row being updated on purpose.
EXPECTED_METRIC_COUNT: Final[int] = 9

_GIT_SHA: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{40}$")


@pytest.fixture(scope="module")
def recorded() -> ShapeBaseline:
    return load_baseline(BASELINE_PATH)


@pytest.fixture(scope="module")
def current() -> ShapeBaseline:
    """One measurement for the module; the ruff child is the only non-hermetic step."""
    return measure(REPO_ROOT, ShapeConfig())


# ---------------------------------------------------------------------------
# Vacuity: the inputs the rule reads must be there and must reach the tree
# ---------------------------------------------------------------------------


def test_the_baseline_is_where_the_tool_writes_it() -> None:
    """A guard reading a different file from the one ``write`` emits guards nothing."""
    assert BASELINE_PATH.is_file(), f"{BASELINE_PATH} is missing; {REGENERATE_HINT}"
    assert BASELINE_PATH == DEFAULT_BASELINE


def test_there_are_exactly_nine_metrics() -> None:
    assert len(METRIC_NAMES) == EXPECTED_METRIC_COUNT
    assert len(set(METRIC_NAMES)) == EXPECTED_METRIC_COUNT


def test_the_baseline_carries_every_metric_and_nothing_else(recorded: ShapeBaseline) -> None:
    assert set(recorded.metrics) == set(METRIC_NAMES)


def test_every_recorded_metric_is_non_negative(recorded: ShapeBaseline) -> None:
    assert all(value >= 0 for value in recorded.metrics.values()), recorded.metrics


def test_the_metrics_reach_the_tree(recorded: ShapeBaseline, current: ShapeBaseline) -> None:
    """All-zero on both sides would mean the roots matched nothing, not a clean tree."""
    assert any(value > 0 for value in recorded.metrics.values()), recorded.metrics
    assert any(value > 0 for value in current.metrics.values()), current.metrics


def test_the_measured_tree_is_not_empty() -> None:
    assert python_files_under(REPO_ROOT / ShapeConfig().src_root)


def test_the_baseline_records_a_real_git_sha(recorded: ShapeBaseline) -> None:
    assert _GIT_SHA.match(recorded.generated_from), recorded.generated_from


def test_the_baseline_was_generated_on_a_clean_tree(recorded: ShapeBaseline) -> None:
    """``generated_from`` must be the revision the numbers came from (PR #151 provenance note).

    ``git_dirty`` counts untracked files, so a baseline written over an
    unstaged ``src/x.py`` records ``true`` here and fails: its numbers
    belong to no commit. The workflow this pins: commit the code, then
    ``write``, then commit the baseline (the tool's own output file is not
    counted as dirt, so that second commit is always reachable).
    """
    assert recorded.git_dirty is False, (
        f"the baseline was written on a dirty tree, so {recorded.generated_from[:12]} cannot "
        f"reproduce its numbers; commit first, then {REGENERATE_HINT}, then commit the baseline"
    )


def test_the_baseline_records_a_hash_for_every_input(recorded: ShapeBaseline) -> None:
    """The committed file must be a full schema-2 record, not a migrated schema-1 one.

    ``load_baseline`` migrates a schema-1 file by recording its one hash
    under ``src`` and nothing else; that keeps ``check`` working but leaves
    hand-edit detection off for the three multi-input metrics. The file in
    the tree may not rely on that leniency.
    """
    assert recorded.schema_version == SHAPE_BASELINE_SCHEMA_VERSION
    assert set(recorded.input_hashes) == set(input_roots(ShapeConfig())), (
        f"inputs recorded {sorted(recorded.input_hashes)} != read "
        f"{sorted(input_roots(ShapeConfig()))}; {REGENERATE_HINT}"
    )
    assert recorded.input_hashes[ShapeConfig().src_root] == recorded.content_hash


def test_the_baseline_ruff_version_matches_the_installed_one(recorded: ShapeBaseline) -> None:
    """Three counts are ruff's; a different ruff makes the comparison meaningless."""
    assert recorded.tool_versions["ruff"] == ruff_version(), (
        f"baseline measured with {recorded.tool_versions['ruff']!r}, installed "
        f"{ruff_version()!r}; align the pin in pyproject.toml's dev extra, then {REGENERATE_HINT}"
    )


def test_the_magic_value_table_is_present_and_sums_to_its_metric(
    recorded: ShapeBaseline,
) -> None:
    assert set(recorded.tables) == set(TABLE_NAMES)
    table = recorded.tables["magic_values"]
    assert table, "an empty table cannot catch a new finding"
    assert sum(table.values()) == recorded.metrics["magic_value_findings"]


# ---------------------------------------------------------------------------
# The rule, one named test per metric
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("metric", METRIC_NAMES)
def test_metric_has_not_grown(metric: str, recorded: ShapeBaseline, current: ShapeBaseline) -> None:
    """Shrink-only: the live measurement may not exceed the recorded count."""
    assert current.metrics[metric] <= recorded.metrics[metric], (
        f"{metric}: measured {current.metrics[metric]} > recorded {recorded.metrics[metric]}. "
        f"The shape grew. Shrink it back, or if the growth is deliberate {REGENERATE_HINT} "
        f"and justify the new number in the change."
    )


@pytest.mark.parametrize("metric", METRIC_NAMES)
def test_recorded_count_is_not_hand_edited(
    metric: str, recorded: ShapeBaseline, current: ShapeBaseline
) -> None:
    """A recorded count above the measurement with its inputs unchanged was typed, not measured.

    Live only while every input *this metric* reads hashes the same as at
    generation (the committed state); once one of them changes the
    improvement is real and regenerating is how it is recorded. Growth is
    owned by ``test_metric_has_not_grown`` and is not re-asserted here.
    """
    unchanged = inputs_unchanged(recorded, current, metric_inputs(ShapeConfig())[metric])
    violation = compare_count(
        metric, recorded.metrics[metric], current.metrics[metric], src_unchanged=unchanged
    )
    if violation is not None and violation.kind == "hand_edited":
        pytest.fail(violation.message)


def test_magic_value_table_has_not_grown(recorded: ShapeBaseline, current: ShapeBaseline) -> None:
    """Per ``(file, rule)``: a new finding cannot hide behind a removal elsewhere."""
    old = recorded.tables["magic_values"]
    new = current.tables["magic_values"]
    grown = {key: (old.get(key, 0), count) for key, count in new.items() if count > old.get(key, 0)}
    assert not grown, f"magic-value findings grew per (file, rule): {grown}; {REGENERATE_HINT}"


def test_the_full_comparison_is_clean(recorded: ShapeBaseline, current: ShapeBaseline) -> None:
    """The CLI's ``check`` and this module apply one function; assert it end to end."""
    violations = compare(recorded, current)
    assert not violations, "\n".join(v.message for v in violations)


# ---------------------------------------------------------------------------
# The rule's own contract (hermetic)
# ---------------------------------------------------------------------------


def test_the_hand_edited_message_names_the_regeneration_command() -> None:
    violation = compare_count("probe", 5, 3, src_unchanged=True)
    assert violation is not None
    assert violation.kind == "hand_edited"
    assert REGENERATE_HINT in violation.message


def test_an_improvement_on_a_changed_tree_is_accepted() -> None:
    assert compare_count("probe", 5, 3, src_unchanged=False) is None


def test_growth_is_a_violation_whatever_the_tree_did() -> None:
    for unchanged in (True, False):
        violation = compare_count("probe", 3, 5, src_unchanged=unchanged)
        assert violation is not None and violation.kind == "grew"


def test_the_two_kinds_are_the_only_kinds() -> None:
    """The per-metric test above dispatches on ``kind``; a third kind would slip past it."""
    assert set(VIOLATION_KINDS) == {"grew", "hand_edited"}
