"""Scaffolding for new AlphaGalerkin agent types (spec-driven).

Generates the spec + agent module + config + mirrored test stub for a new agent
from a single name, so a developer starts from the project's conventions rather
than a blank file. The renderers are pure functions (easy to unit-test); the
orchestrator :func:`scaffold_agent` computes target paths under a repo root and
writes them unless ``dry_run`` is set.

The generated code is intentionally minimal but valid: it subclasses
:class:`~src.agents.base.BaseAgent`, surfaces every knob through a Pydantic
config (no hardcoded values), and ships a test that imports and runs the agent.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "ScaffoldPlan",
    "normalize_agent_name",
    "class_name_for",
    "render_agent_module",
    "render_agent_test",
    "render_spec",
    "scaffold_agent",
]

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def normalize_agent_name(name: str) -> str:
    """Normalize a user-supplied agent name to ``snake_case``.

    Args:
        name: Raw name (e.g. ``"My Agent"`` or ``"my-agent"``).

    Returns:
        A ``snake_case`` identifier (e.g. ``"my_agent"``).

    Raises:
        ValueError: If the normalized name is not a valid identifier.

    """
    normalized = re.sub(r"[\s\-]+", "_", name.strip().lower())
    if not _NAME_RE.match(normalized):
        raise ValueError(
            f"Invalid agent name {name!r}: normalized to {normalized!r}, "
            "which is not a lowercase snake_case identifier."
        )
    return normalized


def class_name_for(snake_name: str) -> str:
    """Return the ``PascalCase`` agent class name for a snake_case name."""
    return "".join(part.capitalize() for part in snake_name.split("_")) + "Agent"


@dataclass(frozen=True)
class ScaffoldPlan:
    """The set of files a scaffold operation will create.

    Attributes:
        name: Normalized snake_case agent name.
        class_name: PascalCase agent class name.
        files: Mapping of target path -> rendered contents.

    """

    name: str
    class_name: str
    files: dict[Path, str]

    @property
    def paths(self) -> list[Path]:
        """Target paths in a deterministic order."""
        return sorted(self.files)


def render_agent_module(name: str, class_name: str) -> str:
    """Render the agent module source for ``src/agents/<name>.py``."""
    return f'''"""Scaffolded {class_name} — fill in the setup/step logic.

Generated by ``python -m src.agents.cli scaffold {name}``. See
``specs/{name}.spec.md`` for the contract this agent must satisfy.
"""

from __future__ import annotations

from src.agents.base import AgentState, BaseAgent
from src.agents.config import AgentConfig, AgentType


class {class_name}(BaseAgent):
    """TODO: describe what {class_name} does."""

    def setup(self) -> None:
        """Initialize resources before the first step."""

    def step(self) -> AgentState:
        """Execute one step and return the updated state."""
        self._state.step += 1
        return self._state

    def reset(self) -> None:
        """Reset to the initial state."""
        self._state = self._create_initial_state()

    def get_metrics(self) -> dict[str, float]:
        """Return current metric values."""
        return {{"step": float(self._state.step)}}


def build_default_config() -> AgentConfig:
    """A default config for {class_name}; every knob is a typed field."""
    return AgentConfig(name="{name}", agent_type=AgentType.META)
'''


def render_agent_test(name: str, class_name: str) -> str:
    """Render the mirrored test stub for ``tests/agents/test_<name>.py``."""
    return f'''"""Tests for {class_name} (scaffolded)."""

from __future__ import annotations

from src.agents.{name} import {class_name}, build_default_config
from src.templates.base import ExecutionStatus


def test_{name}_runs_to_completion() -> None:
    config = build_default_config()
    config.max_steps = 2
    agent = {class_name}(config)
    state = agent.run()
    assert state.status == ExecutionStatus.COMPLETED
    assert state.step == 2
'''


def render_spec(name: str, class_name: str) -> str:
    """Render a spec skeleton for ``specs/<name>.spec.md``."""
    return f"""# Spec: {name}

> **Status:** Draft
> **Primary module(s):** `src/agents/{name}.py`
> **Config class:** `src.agents.config.AgentConfig` (or a dedicated subclass)

## Context

TODO: why {class_name} exists and what gap it fills.

## User Story

**As a** <role>, **I want** <capability>, **so that** <value>.

## Data Contract

Configured by a Pydantic config; every tunable is a typed `Field` (no hardcoded values).

## Acceptance Criteria

### AC1: <name>
- **Given** …
- **When** …
- **Then** …

## Thresholds

Express pass/fail as `src.poc.config.MetricThreshold(name, operator, value)` tuples.

## Regression Surface

```bash
pytest tests/agents/test_{name}.py -v -m "not gpu_required"
```

## Out of Scope

TODO.
"""


def scaffold_agent(name: str, *, root: Path, dry_run: bool = False) -> ScaffoldPlan:
    """Plan (and optionally write) the files for a new agent type.

    Args:
        name: Raw agent name; normalized to snake_case.
        root: Repository root the relative paths are resolved against.
        dry_run: When True, compute the plan without writing any files.

    Returns:
        A :class:`ScaffoldPlan` describing the files (created on disk unless
        ``dry_run``).

    Raises:
        ValueError: If the name is invalid.
        FileExistsError: If any target file already exists (never overwrites).

    """
    snake = normalize_agent_name(name)
    cls = class_name_for(snake)

    files: dict[Path, str] = {
        root / "src" / "agents" / f"{snake}.py": render_agent_module(snake, cls),
        root / "tests" / "agents" / f"test_{snake}.py": render_agent_test(snake, cls),
        root / "specs" / f"{snake}.spec.md": render_spec(snake, cls),
    }

    plan = ScaffoldPlan(name=snake, class_name=cls, files=files)

    if dry_run:
        return plan

    for path in plan.paths:
        if path.exists():
            raise FileExistsError(f"Refusing to overwrite existing file: {path}")

    for path, contents in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")

    return plan
