"""Training and optimization constants for AlphaGalerkin."""

from __future__ import annotations

from src.constants import (
    ATTENTION_EPSILON,
    CHECKPOINT_BEST,
    CHECKPOINT_FINAL,
    DEFAULT_CURRICULUM_SCHEDULE,
    DEFAULT_DROPOUT,
    DEFAULT_PER_ALPHA,
    DEFAULT_PER_BETA,
    DEFAULT_PER_BETA_INCREMENT,
    DEFAULT_TEMPERATURE_SCHEDULE,
    LAYER_NORM_EPSILON,
    NUMERIC_EPSILON,
    WIN_RATE_ACCEPT_THRESHOLD,
    WIN_RATE_REJECT_THRESHOLD,
)

__all__ = [
    "ATTENTION_EPSILON",
    "CHECKPOINT_BEST",
    "CHECKPOINT_FINAL",
    "DEFAULT_CURRICULUM_SCHEDULE",
    "DEFAULT_DROPOUT",
    "DEFAULT_PER_ALPHA",
    "DEFAULT_PER_BETA",
    "DEFAULT_PER_BETA_INCREMENT",
    "DEFAULT_TEMPERATURE_SCHEDULE",
    "LAYER_NORM_EPSILON",
    "NUMERIC_EPSILON",
    "WIN_RATE_ACCEPT_THRESHOLD",
    "WIN_RATE_REJECT_THRESHOLD",
]
